repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Use the same version as in your dependency group
    rev: v0.12.0
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format